
import Main from "./Main";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
