
import Main from "./Main";
import "./globals.css";

export const metadata = {
  title: "Leftap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;600&display=swap" rel="stylesheet" />

      </head>
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
